routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });







// Auth::routes();




Route::get('/timeline', function () {
    return view('comment');
});

// Route::get('dashboard', 'ProfileController@dashboard');



Route::get('noPermission', 'DashboardController@noPermission')->name('noPermission');

Route::post('register', 'Auth\RegisterController@register');

Route::get('register', 'HomeController@register')->name('register');

Route::get( '/', [
  'as' => '/',
  'uses' => 'LoginController@getLogin'
]);


Route::post( 'login', [
  'as' => 'login',
  'uses' => 'LoginController@postLogin'
]);

Route::group(['middleware' => ['authen']], function(){
  Route::post( '/logout', [
    'as' => 'logout',
    'uses' => 'LoginController@getLogout'
  ]);



  Route::post('comments/post/{id}', 'CommentController@store');


  Route::get('/home', 'HomeController@index')->name('home');

  Route::get('me', 'ProfileController@index')->name('me');
  Route::get('me/edit', 'ProfileController@edit');
  Route::put('me/update', 'ProfileController@update')->name('me.update');

  Route::post('me/update-image', 'ProfileController@changeImage')->name('changeImage');

  Route::post('me/update-password', 'ProfileController@changePassword')->name('changePassword');

  Route::get('/dashboard', ['as'=>'dashboard', 'uses'=>'DashboardController@dashboard']);
});

Route::group(['middleware' => ['authen', 'roles'],'roles' => 'reviewer'], function(){
  Route::get('/assessment', function(){
    return view('assessments.index');
  });

  Route::get('assessment/{id}', 'AssessmentController@show');
  Route::put('assessment/{id}', 'AssessmentController@store')->name('assessment');
  Route::get('assessments', 'AssessmentController@index')->name('assessments.index');
});

Route::group(['middleware' => ['authen', 'roles'],'roles' => 'pendamping'], function(){
  Route::get('/monevs', 'MonevController@monev');
  Route::put('approve-monev/{id}', 'MonevController@approveMonev')->name('approveMonev');
  Route::put('unapprove-monev/{id}', 'MonevController@unapproveMonev')->name('unapproveMonev');
  Route::put('approve-research/{id}', 'ResearchController@approveResearch')->name('approveResearch');
  Route::put('unapprove-research/{id}', 'ResearchController@unapproveResearch')->name('unapproveResearch');
  Route::get('advisor/researches', 'ResearchController@advisor')->name('advisor.researches');
  Route::get('advisor/research/seemember/{id}', 'ResearchController@advisorSeeMember')->name('advisor.research.seemember');
  Route::get('advisor/research/{id}/reports', 'MonevController@advisorindex')->name('advisor.research.reports');
  Route::get('advisor/research/{id}', 'ResearchController@advisordetail')->name('advisor.research.detail');
});


Route::group(['middleware' => ['authen', 'roles'],'roles' => 'peneliti'], function(){
  Route::get('research/{id}/reports', 'MonevController@index')->name('research.reports');
  Route::post('research-report/{id}', 'MonevController@store')->name('research.report');
  Route::get('research', 'ResearchController@me');
  Route::get('research/addmember/{id}', 'ResearchController@addmember')->name('research.addmember');
  Route::post('research/addingmember/{id}', 'ResearchController@addingmember')->name('research.addingmember');
  Route::post('research/removemember/{id}', 'ResearchController@removemember')->name('research.removemember');
  Route::get('research/{id}', 'ResearchController@detail')->name('research.detail');
  Route::post('research', 'ResearchController@store')->name('research.store');
  Route::put('research/{id}', 'ResearchController@update')->name('research.update');
  Route::get('research/show/{id}', 'ResearchController@show')->name('research.show');
  Route::get('all', 'ResearchController@all');
});

Route::group(['middleware' => ['authen', 'roles'],'roles' => 'operator'], function(){
  Route::resource('researches', 'ResearchController');
  Route::put('update-reviewer/{id}', 'ResearchController@selectReviewer')->name('selectReviewer');
  Route::get('operator/research/{id}', 'ResearchController@advisordetail')->name('operator.research.detail');
});

Route::group(['middleware' => ['authen', 'roles'],'roles' => 'administrator'], function(){
  Route::get('/roles', 'RoleController@index');
  Route::put('user/update-role/{id}', 'UserController@changeRole')->name('changeRole');
  Route::get('administrator/researches', 'ResearchController@administrator')->name('administrator.researches');
  Route::resource('users', 'UserController');
  Route::get('administrator/research/{id}', 'ResearchController@administratordetail')->name('administrator.research.detail');
});

resources/views/layouts/partials/footer.blade.php
<footer class="main-footer">
  <div class="pull-right hidden-xs">
    <b>Version</b> 1.0.0
  </div>
  <strong>Copyright &copy; 2017 <a href="#!"></a>.</strong> All rights
  reserved.
</footer>

resources/views/layouts/partials/header.blade.php
<header class="main-header">
  <!-- Logo -->
  <a href="#!" class="logo">
    <!-- mini logo for sidebar mini 50x50 pixels -->
    <span class="logo-mini"><b>H</b></span>
    <!-- logo for regular state and mobile devices -->
    <span class="logo-lg"><b>HIBAH</b></span>
  </a>
  <!-- Header Navbar: style can be found in header.less -->
  <nav class="navbar navbar-static-top">
    <!-- Sidebar toggle button-->
    <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
      <span class="sr-only">Toggle navigation</span>
    </a>

    <div class="navbar-custom-menu">
      <ul class="nav navbar-nav">
        <!-- Messages: style can be found in dropdown.less-->

        <li>
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            <span class="hidden-xs"><strong>{{ Auth::user()->name }}</strong></span>
          </a>
        </li>
        <li class="dropdown user user-menu">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            <span class="hidden-xs"><i class="fa fa-gears"></i></span>
          </a>
          <ul class="dropdown-menu">
            <!-- User image -->
            <li class="user-header">
              <p>
                {{ Auth::user()->name }} - {{ Auth::user()->role->name }}
              </p>
            </li>

            <!-- Menu Footer-->
            <li class="user-footer">
              <div class="pull-left">
                <a href="{{ url('me') }}" class="btn btn-default btn-flat">Profile</a>
              </div>
              <div class="pull-right">
                <form class="" action="{{ route('logout') }}" method="post">
                  {{ csrf_field() }}
                  <button class="btn btn-default btn-flat" type="submit">Logout</button>
                </form>
              </div>
            </li>
          </ul>
        </li>
      </ul>
    </div>
  </nav>
</header>

resources/views/layouts/partials/sidebar.blade.php
<aside class="main-sidebar">
  <!-- sidebar: style can be found in sidebar.less -->
  <section class="sidebar">
    <!-- search form -->
    <!-- <form action="#" method="get" class="sidebar-form">
      <div class="input-group">
        <input type="text" name="q" class="form-control" placeholder="Search...">
            <span class="input-group-btn">
              <button type="submit" name="search" id="search-btn" class="btn btn-flat"><i class="fa fa-search"></i>
              </button>
            </span>
      </div>
    </form> -->
    <!-- /.search form -->
    <!-- sidebar menu: : style can be found in sidebar.less -->
    <ul class="sidebar-menu">
      <li class="header">MAIN NAVIGATION</li>

      <!-- <li>
        <a href="{{ url('dashboard') }}">
          <i class="fa fa-dashboard"></i> <span>Dashboard</span>
        </a>
      </li> -->

      @if( Auth::user()->role->name == 'peneliti' )

      <li>
        <a href="{{ url('research') }}">
          <i class="fa fa-dashboard"></i> <span>Penelitian</span>
        </a>
      </li>
      <li>
        <a href="{{ url('all') }}">
          <i class="fa fa-list"></i> <span>Penelitian</span>
        </a>
      </li>

      @elseif( Auth::user()->role->name == 'operator' )

      <li>
        <a href="{{ route('researches.index') }}">
          <i class="fa fa-search"></i> <span>Penelitian</span>
        </a>
      </li>

      @elseif( Auth::user()->role->name == 'reviewer' )

      <li>
        <a href="{{ route('assessments.index') }}">
          <i class="fa fa-sort-numeric-asc"></i> <span>Penilaian</span>
        </a>
      </li>

      @elseif( Auth::user()->role->name == 'pendamping' )

      <li class="treeview active">
        <a href="#">
          <i class="fa fa-cubes"></i>
          <span>Menu</span>
          <span class="pull-right-container">
            <i class="fa fa-angle-left pull-right"></i>
          </span>
        </a>
        <ul class="treeview-menu">
          <li><a href="{{ route('advisor.researches') }}"><i class="fa fa-circle-o"></i> Penelitian</a></li>
          <li><a href="{{ url('monevs') }}"><i class="fa fa-circle-o"></i> Laporan Monev</a></li>
        </ul>
      </li>

      @elseif( Auth::user()->role->name == 'administrator' )

      <li class="treeview active">
        <a href="#">
          <i class="fa fa-users"></i>
          <span>Manajemen Pengguna</span>
          <span class="pull-right-container">
            <i class="fa fa-angle-left pull-right"></i>
          </span>
        </a>
        <ul class="treeview-menu">
          <li><a href="{{ route('users.index') }}"><i class="fa fa-circle-o"></i> Pengguna</a></li>
          <li><a href="{{ url('roles') }}"><i class="fa fa-circle-o"></i> Peran</a></li>
          <li><a href="{{ route('administrator.researches') }}"><i class="fa fa-circle-o"></i> Penelitian</a></li>
        </ul>
      </li>

      @endif




      <!-- <li class="treeview">
        <a href="#">
          <i class="fa fa-pie-chart"></i>
          <span>Charts</span>
          <span class="pull-right-container">
            <i class="fa fa-angle-left pull-right"></i>
          </span>
        </a>
        <ul class="treeview-menu">
          <li><a href="pages/charts/chartjs.html"><i class="fa fa-circle-o"></i> ChartJS</a></li>
          <li><a href="pages/charts/morris.html"><i class="fa fa-circle-o"></i> Morris</a></li>
          <li><a href="pages/charts/flot.html"><i class="fa fa-circle-o"></i> Flot</a></li>
          <li><a href="pages/charts/inline.html"><i class="fa fa-circle-o"></i> Inline charts</a></li>
        </ul>
      </li> -->



      <!-- <li><a href="documentation/index.html"><i class="fa fa-book"></i> <span>Documentation</span></a></li>
      <li class="header">LABELS</li>
      <li><a href="#"><i class="fa fa-circle-o text-red"></i> <span>Important</span></a></li>
      <li><a href="#"><i class="fa fa-circle-o text-yellow"></i> <span>Warning</span></a></li>
      <li><a href="#"><i class="fa fa-circle-o text-aqua"></i> <span>Information</span></a></li> -->
    </ul>
  </section>
  <!-- /.sidebar -->
</aside>